[theme]

# Primary accent for interactive elements
primaryColor = '#3E07B4'

# Background color for the main content area
backgroundColor = '#A596F4'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#D3CFF6'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"